### ISSUE TITLE
Euler angles are absent if in 'CAS' and 'NAV' devices barometer priority is primary for both

### ISSUE THREAD

**Issue by SlavaVasiukovich** [uavos/apx-ap#1]
**Environment:**
APX Firmware - 11.0.50
GCU version - APX_Ground_Control-11.0.134-linux-x86_64

**Log for actual result:**
[vs_nav.vehicle.txt](https://github.com/uavos/apx-ap/files/6330798/vs_nav.vehicle.txt)
_Please, to view the conf file remove **txt** extension from the end of the file name._ 

**Note**
If in 'CAS' or 'NAV' devices barometer priority is 'off' or 'local', all works as expected

**Comment by uavinda** [comment]
Checked. This is made intentionally:
- there must be at least one height source to initialize AHRS;
- there must never be same data sources configured for the same priority;
